/**
 * Google analytics tracking code
 * Version 3.3
 * Released on 02.03.2012
 * Website: http://www.ga-script.org
 * 
 * Copyright (c) 2011 Pavel Sabatka
 * Copyright (c) JP Consult s.r.o.
 * 
 * With kind compliance of Jan Tichy uses list of search engines from H1 tracking code 
 * @see http://www.h1.cz/ga
 */
if(typeof console=="undefined"||typeof console.log=="undefined")var console={log:function(){}};var _gas={},_gaq=_gaq||[];(function(){var a=document.createElement("script");a.type="text/javascript";a.async=!0;a.src=("https:"==document.location.protocol?"https://ssl":"http://www")+".google-analytics.com/ga.js";var b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)})();
_gas._constructRouter=function(){this.Router=function(){function a(c,f){var a=c?c:document.location.href,f=!!f;if(d[c]!=void 0)return d[c];for(var a=_gas.lib.prepareUrl(a,!0),h=0;h<b.length;h++)if(b[h].match(a))return f&&b[h].exec(),d[c]=b[h].assemble(a),d[c];return a}var b=[],d=[];this.addRoute=function(c){b[b.length]=c};this.getUrl=function(c){return a(c,!1)};this.processAfterDomReady=function(c){var c=c?c:document.location.href,c=_gas.lib.prepareUrl(c,!0),f;for(f in b)if(_gas.lib.isInt(f))if(b[f].processAfterDomReady(c))return!0;
else if(b[f].match(c))break;return!1};this.getUrlAndExec=function(c){return a(c,!0)};this.clear=function(){b=[]}}};_gas._constructRouter();
_gas._constructTracker=function(){this.Tracker=function(a){var b=a==void 0?"":a;this.push=function(a){if(_gas.lib.isArray(a)){if(a.length==0)throw"Exception expected: empty array";var c=a.slice(0);c[0]=(b.length==0?"":b+".")+a[0];return _gaq.push(c)}else if(_gas.lib.isFunction(a))return _gaq.push(a);else throw"Exception expected: not array value";};this.getName=function(){return b}}};_gas._constructTracker();
_gas._constructGa=function(){function a(c,b){for(var f in b)if(_gas.lib.isInt(f)){var a=b[f];if(a.length!=0){var d=!1,e=a[0];_gas.lib.strpos(a[0],".")!==!1&&(e=a[0].split("."),d=e[0],e=e[1]);d&&c.getName()!=d||(a[0]=e,c.push(a))}}}this.addOrganics=!0;var b=new _gas.tracker.Container,d=[],c=[],f="auto";this.onReady=new _gas.service.OnReady(jQuery);var e="oneDomain",h=!1,g=["atlas.centrum.cz:q","atlas.cz:q","m.search.seznam.cz:srch","hyperceny.cz:q","ishopy.eu:search","centrum.cz:q","1188.cz:q","jyxo.cz:q",
"mapy.cz:ssq","najisto.centrum.cz:what","takeit.cz:q","seznam.cz:q","seznam.cz:w","searchatlas.centrum.cz:q","tiscali.cz:query","volny.cz:search","1.cz:q","akcni-cena.cz:search","b2bc.cz:XSearching","ceno.cz:q","cenyzbozi.cz:q","dobra-koupe.cz:searchtext","elektro.cz:w","elektrus.cz:h","eshop-katalog.cz:hledej","foxter.cz:search","heureka.cz:h[fraze]","hledam-zbozi.cz:q","hledejceny.cz:search","webhledani.cz:q","zacatek.cz:q","zlatestranky.cz:search","zoohoo.cz:q","koupis.cz:q","lepsiceny.cz:q","levnenakupy.cz:searchword",
"mojse.cz:search_text","monitor.cz:qw","naakup.cz:hledat","najdicenu.cz:ss","nakupte.cz:what","nejlepsiceny.cz:t","nejlepsinakupy.cz:q","nejnakup.cz:q","onlinezbozi.cz:search","porovnejcenu.cz:phrase","seznamobchodu.cz:search","seznamzbozi.cz:st","shoops.cz:s","shopy.cz:s","srovname.cz:hledat","srovnanicen.cz:q","srovnavadlo.cz:q","taxa.cz:keyword","usetrim.cz:q","vybereme.cz:q","atlas.sk:phrase","centrum.sk:q","azet.sk:q","azet.sk:sq","morfeo.sk:q","surf.sk:kw","szm.sk:ws","zoohoo.sk:q","zoznam.sk:s",
"cenoveinfo.sk:SearchProductName","e-nakupovanie.sk:searchword","heureka.sk:h[fraze]","najdicenu.sk:ss","najnakup.sk:q","nakup.24hod.sk:q","srovname.sk:hledat","superdeal.sk:q","tovar.sk:q","google:q","google:as_q","google:as_oq","google:as_epq","google:as_lq","google:as_rq","ananzi.co.za:qt","anzwers.com.au:search","araby.com:q","bbc.co.uk:q","britishinformation.com:search","club-internet.fr:q","elmundo.es:q","eniro.se:geo_area","excite.co.uk:q","excite.com:q","gigablast.com:q","hotbot.co.uk:query",
"hotbot.com:query","iafrica.funnel.co.za:q","icq.com:q","kelkoo:contextKeywords","looksmart.com:qt","maktoob.com:q","myway.com:searchfor","mywebsearch.com:searchfor","najdi.si:q","netsprint.pl:q","onet.pl:qt","orange.co.uk:q","rambler.ru:query","search.com:q","searcheurope.com:query","searchy.co.uk:search_term","sky.com:term","suche.web.de:su","tesco.net:q","tiscali.co.uk:query","virginmedia.com:q","wolframalpha.com:i","zinza.com:query","yandex.com:text","baidu.com:wd","zalevno.cz:q","zbozi.eshop-katalog.cz:hledej",
"zbozi.poptavky.cz:cond[fulltext]","zbozi.portik.cz:vyraz","zbozi.cz:q"],m,n=new _gas.Router,j=new _gas.tracker.HttpStatus(b),o=!1,l=!1;this.youtube=new _gas.net.YouTube(b);this.twitter=new _gas.net.Twitter(b);this.setSocialActionsTrackedAlsoAsEvents=function(c){h=!!c};this.setConfigType=function(c){switch(c){case 3:case "moreDomains":e=3;break;case 2:case "moreSubdomains":e=2;break;case 1:case "oneDomain":e=1;break;default:console.log("Invalid type "+c)}};this.create=function(m,h){try{l=!0;var j=
new _gas.Tracker(h);j.push(["_setAccount",m]);j.push(["_setAllowAnchor",!0]);switch(e){case 3:j.push(["_setAllowLinker",!0]);case 2:if(j.push(["_setAllowHash",!1]),f=="auto")throw"_gas error: domain must be set";}var o,q;if(this.addOrganics)for(q=g.length-1;q>=0;q--)o=g[q].split(":"),j.push(["_addOrganic",o[0],o[1],!0]);o=function(f){a(f,d);f.push(["_trackPageview",n.getUrlAndExec()]);b.addTracker(f);a(f,c)};n.processAfterDomReady()?this.onReady.addAction(o,j):o(j)}catch(s){console.log(s)}};this.push=
function(a){if(_gas.lib.isArray(a)&&a.length>0&&_gas.lib.strpos(a[0],"_setDomainName")!==!1){a.length!=2&&console.log("_gas warning: _setDomainName must have 1 param!");var e=a[0],m=a[1];o?console.log("_gas warning: _setDomainName can be called only once!"):(f=m,o=!0);_gas.lib.strpos(e,".")&&console.log("_gas warning: do not use _setDomainName for specific trackers!");if(m!="auto"){var e=location.hostname,g=m.replace(/\./g,"\\."),g="^"+(m[0]=="."?"(.*)":"(.*\\.|)")+g+"$";e.match(RegExp(g))||console.log("_gas warning: domain "+
m+" does not match with actual domain "+e)}}if(l)if(b.hasAnyTracker())try{b.push(a)}catch(h){console.log(h)}else c[c.length]=a;else d[d.length]=a};this.addRoute=function(c){try{n.addRoute(c)}catch(b){console.log(b)}};this.init=function(c,a){c.XFBML!=void 0?(new _gas.net.Facebook(b,h)).init(c,a):c.target!=void 0&&_gas.lib.isFunction(c.target.playVideo)?this.youtube.addJsVideo(c,a):(console.log(c),console.log(a))};this.initOnReady=function(){this.youtube.init(jQuery);this.twitter.init(jQuery,h);m=new _gas.tracker.Links(this);
m.init(jQuery);j.init(jQuery)};this.onReady.addAction("initOnReady");this.enableErrorTrancking=function(){j.setEnabled()};this.clear=function(){b.clear();n.clear();d=[];c=[];f="auto";l=o=!1;e="oneDomain"}};_gas.lib={};_gas.lib._constructTimer=function(){this.Timer=function(a,b,d){var c=!1,f=!1;this.start=function(e){e<0||(this.isRunning()&&this.stop(),f=setTimeout('window["'+a+'"]("'+b+'", "'+d+'")',e),c=!0)};this.stop=function(){clearTimeout(f);c=!1};this.isRunning=function(){return c}}};_gas.lib._constructTimer();
_gas.lib._construct=function(){this.implode=function(a,b){return b instanceof Array?b.join(a):b};this.isFunction=function(a){return typeof a=="function"&&(!Function.prototype.call||typeof a.call=="function")};this.inArray=function(a,b){for(var d=b.length,c=0;c<d;c++)if(b[c]==a)return!0;return!1};this.trim=function(a){return a.replace(/^\s*|\s*$/g,"")};this.isArray=function(a){return a.constructor.toString().indexOf("Array")==-1?!1:!0};this.time=function(a){var b=(new Date).getTime()/1E3;return a?
b:round(b)};this.strpos=function(a,b,d){a=(a+"").indexOf(b,d||0);return a===-1?!1:a};this.isInt=function(a){var b=parseInt(a);if(isNaN(b))return!1;return a==b&&a.toString()==b.toString()}};_gas.lib._construct();
_gas.lib._constructUrlPrepare=function(){this.prepareUrl=prepareUrl=function(a,b){if(a[0]=="#")return a;a=a.replace(/^https?:\/\//i,"");a=a.replace(/#.*$/i,"");a=a.replace(RegExp("^"+location.hostname+"(:[0-9]{2,4})?"),"");b||(a=a.replace(/\?.*/,""));a=a.replace(/\/\?/,"?");a=a.replace(/\/$/,"");/^\//.test(a)||(a="/"+a);return a}};_gas.lib._constructUrlPrepare();_gas.net={};
_gas.net._constructFacebook=function(){this.Facebook=function(a,b){this._trackers=a;this._trackedEvents=[];this._fireAlsoEvent=!!b;this.trackSocial=function(a,c){_gas.lib.inArray(c,a._trackedEvents)||(a._trackers.push(["_trackSocial","Facebook",c]),a._trackedEvents[a._trackedEvents.length]=c,a._fireAlsoEvent&&a._trackers.push(["_trackEvent","Social","Facebook",c]))};this.init=function(a){var c=this;try{a.Event.subscribe("edge.create",function(){_gas.lib.inArray("Like",c._trackedEvents)||(c._trackers.push(["_setCustomVar",
1,"Facebook","FB Liker",5]),c._trackers.push(["_trackSocial","Facebook","Like"]),c._trackedEvents[c._trackedEvents.length]="Like",c._fireAlsoEvent&&c._trackers.push(["_trackEvent","Social","Facebook","Like"]))}),a.Event.subscribe("edge.remove",function(){_gas.lib.inArray("Unlike",c._trackedEvents)||(c._trackers.push(["_deleteCustomVar",5]),c._trackers.push(["_trackSocial","Facebook","Unlike"]),c._trackedEvents[c._trackedEvents.length]="Unlike",c._fireAlsoEvent&&c._trackers.push(["_trackEvent","Social",
"Facebook","Unlike"]))}),a.Event.subscribe("xfbml.render",function(){a.Event.subscribe("edge.create",function(){_gas.lib.inArray("Like",c._trackedEvents)||(c._trackers.push(["_setCustomVar",1,"Facebook","FB Liker",5]),c._trackers.push(["_trackSocial","Facebook","Like"]),c._trackedEvents[c._trackedEvents.length]="Like",c._fireAlsoEvent&&c._trackers.push(["_trackEvent","Social","Facebook","Like"]))});a.Event.subscribe("edge.remove",function(){_gas.lib.inArray("Unlike",c._trackedEvents)||(c._trackers.push(["_deleteCustomVar",
5]),c._trackers.push(["_trackSocial","Facebook","Unlike"]),c._trackedEvents[c._trackedEvents.length]="Unlike",c._fireAlsoEvent&&c._trackers.push(["_trackEvent","Social","Facebook","Unlike"]))})}),a.Event.subscribe("comment.create",function(){c.trackSocial(c,"Comment create")}),a.Event.subscribe("comment.remove",function(){c.trackSocial(c,"Comment remove")}),a.Event.subscribe("auth.login",function(){c.trackSocial(c,"Login")}),a.Event.subscribe("auth.logout",function(){c.trackSocial(c,"Logout")})}catch(b){}}}};
_gas.net._constructFacebook();
_gas.net._constructTwitter=function(){this.Twitter=function(a,b){function d(a){if(!a)return"";a=a.split("#")[0];a=a.split("?");if(a.length==1)return"";for(var a=decodeURI(a[1]).split("&"),c=0,b;b=a[c];++c)if(b.indexOf("url=")===0)return unescape(b.split("=")[1]);return""}var c=!!b;this.init=function(){window.twttr&&window.twttr.events&&(window.twttr.events.bind("tweet",function(a){a&&_gas.twitter.track("tweet",a.target&&a.target.nodeName=="IFRAME"?a.target.src:void 0)}),window.twttr.events.bind("follow",
function(a){a&&_gas.twitter.track("follow",a.target&&a.target.nodeName=="IFRAME"?a.target.src:void 0)}),window.twttr.events.bind("retweet",function(a){a&&_gas.twitter.track("retweet",a.target&&a.target.nodeName=="IFRAME"?a.target.src:void 0)}),window.twttr.events.bind("favorite",function(a){a&&_gas.twitter.track("retweet",a.target&&a.target.nodeName=="IFRAME"?a.target.src:void 0)}))};this.track=function(b,e){e&&(e=d(e));a.push(["_trackSocial","Twitter",b,e]);c&&a.push(["_trackSocial","Social","Twitter",
b])}}};_gas.net._constructTwitter();
_gas.net._constructYouTube=function(){this.YouTube=function(a){var b=[];this.tracker=new _gas.net.youtube.StateTracker(a);var d=0,c=this;this.init=function(a){var c=this;a("embed").each(function(){c.initVideo(c,this)})};this.getCodeFromSrc=function(a){var c=void 0;/www\.youtube\.com\/embed\/.+/.test(a)?c=a.replace(/^.*\/embed\//,""):(c=a.replace(/^.*\/v\//,""),c=c.replace(/^.*(\?|&|\/)v=/,""));return c=c.replace(/(\?|&|\/).*$/,"")};this.initVideo=function(a,e){var d=e.src;if(/www\.youtube\.com/.test(d)){var g=
null,m=!1,n="",j=this.getCodeFromSrc(e.src);/playerapiid=/.test(d)?(m=!0,g=d.replace(/^.*playerapiid=/,""),g=g.replace(/[^a-zA-Z0-9_\-+].*$/,"")):g=e.id.length>0?e.id:a.getAutoId();e.id=g;/enablejsapi=1/.test(d)||(n="enablejsapi=1");m||(n+=(n.length>0?"&":"")+"playerapiid="+g);if(n.length>0)d+=(/\?/.test(d)?"&":"?")+n,e.src=d,jQuery.browser.mozilla||($("embed#"+g).replaceWith('<div id="'+g+'"></div>'),$("div#"+g).replaceWith(e));j=c.getCodeFromSrc(e.src);d=new _gas.net.youtube.api.Embed;g=new _gas.net.youtube.Video(g,
j,e,this.tracker,d);b.push(g)}};this.getVideo=function(a){for(var c in b)if(_gas.lib.isInt(c)&&b[c].id==a)return b[c];return null};this.addVideo=function(a){b[b.length]=a};this.getVideoByCode=function(a){for(var c in b)if(_gas.lib.isInt(c)&&b[c].ytcode==a)return b[c];return null};this.getAutoId=function(){var a="ytvideoplayer"+d;d++;return a};this.getVideos=function(){return b};this.addJsVideo=function(a,c){jQuery(document).ready(function(){var b=_gas.youtube,d=a.target,m=b.getAutoId(),n=d.getVideoUrl();
if(n!=void 0){n=b.getCodeFromSrc(n);c&&(d.addEventListener("onStateChange",window._gas.youtube.trackEvent),d.addEventListener("onError",window._gas.youtube.trackError));var j=new _gas.net.youtube.api.Js,d=new _gas.net.youtube.Video(m,n,d,b.tracker,j);b.addVideo(d)}})};this.trackEvent=function(a){try{if(_gas.lib.isFunction(a.target.getVideoData))ytCode=a.target.getVideoData().video_id;else{var c=["a","b","c","d","e","f","g","h","i","j","k","l","m","n"],b;for(b in c)if(_gas.lib.isInt(b)&&c[b]in a.target&&
"videoData"in a.target[c[b]]){ytCode=a.target[c[b]].videoData.video_id;break}}if(ytCode!=void 0){var d=_gas.youtube.getVideoByCode(ytCode);d&&d.youtubeEvent(a.data)}}catch(m){console.log(m)}};this.trackError=function(a){try{var c=_gas.youtube.getCodeFromSrc(a.target.a.videoUrl);_gas.youtube.getVideoByCode(c).youtubeError(a.data)}catch(b){console.log(b)}};this.onYouTubePlayerReady=function(a){a&&typeof _gas.youtube==="object"&&_gas.youtube.getVideo(a).initEvents()}}};_gas.net._constructYouTube();
_gas.net.youtube={};
_gas.net.youtube._constructStateTracker=function(){this.StateTracker=function(a){this.trackState=function(b,d){d*=1;var c=_gas.lib.time(!0),f;b.timer.isRunning()&&(b.seenSeconds+=c-b.lastEventTime);switch(d){case 1:b.playClickCount++;if(!b.playStarted)b.seenSeconds=0,b.playStarted=!0,a.push(["_trackEvent","YouTube",b.ytcode,"0% - Play started",b.playClickCount]);f=(b.trackedEvents+1)*b.getDuration()/10-b.seenSeconds;b.timer.start(f*1E3);break;case 91:if(b.timer.isRunning())b.trackedEvents++,b.lastEventTime=
c,a.push(["_trackEvent","YouTube",b.ytcode,b.trackedEvents*10+"%",b.playClickCount]);f=(b.trackedEvents+1)*b.getDuration()/10-b.seenSeconds;b.timer.start(f*1E3);break;default:b.timer.stop()}b.lastEventTime=c};this.trackError=function(b){a.push(["_trackEvent","YouTube",b.ytcode,"Error",b.seenSeconds])}}};_gas.net.youtube._constructStateTracker();
_gas.net.youtube._constructVideo=function(){this.Video=function(a,b,d,c,f){this.id=a;this.ytcode=b;this.playStarted=!1;this.seenSeconds=0;this.lastStop=!1;this.timer=new _gas.lib.Timer("_gaYouTubeTimerEventHandler",this.id,91);this.trackedEvents=0;this.duration=this.lastEventTime=!1;this.playClickCount=0;this.initEvents=function(){f.initEvents(d,this.id)};this.youtubeEvent=function(a){c.trackState(this,a)};this.youtubeError=function(a){c.trackError(this,a)};this.getDuration=function(){if(!this.duration)this.duration=
d.getDuration()-1;return this.duration}}};_gas.net.youtube._constructVideo();_gas.net.youtube.api={};
_gas.net.youtube.api._constructEmbed=function(){this.Embed=function(){this.initEvents=function(a,b){a.addEventListener?(a.addEventListener("onStateChange","_gas.youtube.getVideo('"+b+"').youtubeEvent"),a.addEventListener("onError","_gas.youtube.getVideo('"+b+"').youtubeError")):(a.attachEvent("onStateChange","_gas.youtube.getVideo('"+b+"').youtubeEvent"),a.attachEvent("onError","_gas.youtube.getVideo('"+b+"').youtubeError"))}}};_gas.net.youtube.api._constructEmbed();
_gas.net.youtube.api._constructJs=function(){this.Js=function(){this.initEvents=function(){}}};_gas.net.youtube.api._constructJs();function onYouTubePlayerReady(a){_gas.youtube.onYouTubePlayerReady(a)}function _gaYouTubePlayerReady(a){_gas.init(a,!0)}function _gaYouTubeTimerEventHandler(a,b){try{_gas.youtube.getVideo(a).youtubeEvent(b)}catch(d){console.log(d)}}_gas.route={};
_gas.route._constructBase=function(){this.Base=function(a,b,d){function c(){if(g==void 0){var a=e.replace(/\$[0-9]+/gi,"([^/?&]+)"),a=a.replace(/\/+/g,"\\/"),a=a.replace(/\?/g,"\\?"),a=_gas.lib.strpos(e,"?")?"^"+a:"^"+a+"$";g=RegExp(a)}return g}function f(){var a=h.match(/(\$[0-9]+)/gi);return a==null?[]:a}var e=_gas.lib.prepareUrl(a,!0),h=b,g;this.match=function(a){a=_gas.lib.prepareUrl(a,_gas.lib.strpos(e,"?"));return c().test(a)};this.assemble=function(a){if(!this.match(a))throw"URL "+a+" does not match route "+
e;var b;_gas.lib.strpos(e,"?")?(b=a.replace(c(),""),b=b.replace(/^[?&/]*/,"")):b=_gas.lib.strpos(a,"?")?a.replace(/^(.*)\?/,""):"";var d=h;_gas.lib.strpos(e,"?")?(a=_gas.lib.prepareUrl(a,!0),query=a.replace(c(),""),a=a.replace(query,"")):a=_gas.lib.prepareUrl(a);var g=f(),l=[];for(i=0;i<g.length;i++){var k=e,k=k.replace(RegExp("\\"+g[i]),"$~"+i+"~"),k=k.replace(/\$[0-9]+/g,"([^/]+)"),k=k.replace(/\/+/g,"\\/"),p=k.replace(RegExp("\\$~"+i+"~(.*)$"),""),k=k.replace(RegExp("^(.*)\\$~"+i+"~"),""),p=p.replace("?",
"\\?"),k=k.replace("?","\\?"),p=a.replace(RegExp(p),""),p=p.replace(RegExp(k),"");l[g[i]]=p}for(var r in l)d=d.replace(RegExp("\\"+r,"g"),l[r]);b.length>0&&(d.match(/^(.*)\?(.+)$/)?d=d+"&"+b:d.match(/^(.*)\?$/)?d+=b:d=d+"?"+b);return d};this.processAfterDomReady=function(){return!1};this.exec=function(){_gas.lib.isFunction(d)&&d()};if(!function(){for(var a=f(),c=0;c<a.length;c++)if(!e.match(RegExp("\\"+a[c])))return!1;return!0}())throw"Created route is not valid: count of var in URL is lower then length of array, first var is $1 (not a $0)!";
}};_gas.route._constructBase();_gas.route._constructConditionOnUrl=function(){this.ConditionOnUrl=function(a,b,d,c){var f=new _gas.route.Base(a,b,c);this.match=function(a){return d(a)&&f.match(a)};this.assemble=function(a){if(!d(a))throw"URL "+a+" does not match route";return f.assemble(a)};this.exec=function(){f.exec()};this.processAfterDomReady=function(a){return f.match(a)};if(!_gas.lib.isFunction(d))throw"condition must be a function!";}};_gas.route._constructConditionOnUrl();
_gas.route._constructCustomVariable=function(){this.CustomVariable=function(a,b,d,c){function f(){var a=h.match(/(\$[0-9]+)/gi);return a==null?[]:a}var e=_gas.lib.prepareUrl(a),h=b;this.match=function(a){var a=_gas.lib.prepareUrl(a),c=e.replace(/\$[0-9]+/gi,"([^/]+)"),c=c.replace(/\/+/g,"\\/");return RegExp("^"+c+"$").test(a)};this.assemble=function(a){var c=a.match(/\?/)?a.replace(/^(.*)\?/,""):"";if(!this.match(a))throw"URL "+a+" does not match route "+e;var b=h,a=_gas.lib.prepareUrl(a),j=f(),o=
[];for(i=0;i<j.length;i++){var l=e;if(RegExp("\\"+j[i]).test(l)){var l=l.replace(RegExp("\\"+j[i]),"$~"+i+"~"),l=l.replace(/\$[0-9]+/g,"([^/]+)"),l=l.replace(/\/+/g,"\\/"),k=l.replace(RegExp("\\$~"+i+"~(.*)$"),""),l=l.replace(RegExp("^(.*)\\$~"+i+"~"),""),k=a.replace(RegExp(k),""),k=k.replace(RegExp(l),"");o[j[i]]=k}else k=j[i].replace(/^\$/,""),o[j[i]]=d(k)}for(var p in o)b=b.replace(RegExp("\\"+p,"g"),o[p]);c.length>0&&(b.match(/^(.*)\?(.+)$/)?b=b+"&"+c:b.match(/^(.*)\?$/)?b+=c:b=b+"?"+c);return b};
this.exec=function(){_gas.lib.isFunction(c)&&c()};this.processAfterDomReady=function(){return!0};if(function(){for(var a=f(),c=0;c<a.length;c++)if(a[c]!="$"+(c+1))return!1;return!0}()){if(!_gas.lib.isFunction(d))throw"loadParam must be javascript function";}else throw"Created route is not valid: count of var in URL is lower then length of array, first var must be $1 (not a $0)!";}};_gas.route._constructCustomVariable();
_gas.route._constructDrupalSearch=function(){this.DrupalSearch=function(a,b){function d(){var a=location.pathname,a=a.replace(/^.*\/search\/node\//,"");return a=a.replace(/[/?&#].*$/,"")}this.match=function(a){return _gas.lib.strpos(a,"search/node")!==!1};this.assemble=function(a){if(!this.match(a))throw"URL "+a+" does not match route "+_route;var a=a.split("?"),b=a[0].split("search/node"),d=b[1].replace(/^\//,"");return b[0]+"search?q="+d+(a.length==1?"":"&"+a[1])};this.exec=function(){_gas.lib.isFunction(b)&&
b();_gas.lib.isFunction(a)&&_gas.onReady.addAction(function(){_gas.push(["_trackEvent","Search",""+d(),""+a()])})};this.processAfterDomReady=function(){return!1}}};_gas.route._constructDrupalSearch();
_gas.route._constructRegexp=function(){this.Regexp=function(a,b,d){this.trackAfterDomReady=!0;var c=b?_gas.lib.prepareUrl(b,!0):b;this.match=function(c){return a.test(c)};this.assemble=function(b){if(!this.match(b))throw"URL "+b+" does not match route "+a;if(!c)return b;var d=c;/\?/.test(b)&&(b=b.replace(/^.*\?/,""),d+=(/\?/.test(d)?"&":"?")+b);return d};this.processAfterDomReady=function(){return!1};this.exec=function(){_gas.lib.isFunction(d)&&d()}}};_gas.route._constructRegexp();
_gas.route._constructSearch=function(){this.Search=function(a,b,d,c,f){var e,h=!1;this.match=function(a){return e.match(a)};this.assemble=function(a){return e.assemble(a)};this.exec=function(a){e.exec();h||(h=!0,a&&_gas.lib.isFunction(c)&&_gas.lib.isFunction(d)&&a(document).ready(function(){_gas.push(["_trackEvent","Search",""+d(),""+c()])}))};this.processAfterDomReady=function(){return!1};e=new _gas.route.Base(a,b?b:a,f)}};_gas.route._constructSearch();
_gas.route._constructWPSearch=function(){this.WPSearch=function(a,b){var d=new _gas.route.Search("/?q=$1","/search?q=$1",function(){var a=location.pathname,a=a.replace(/^\/\?q=/,"");return a=a.replace(/[^/?&]*$/,"")},a,b);this.match=function(a){return d.match(a)};this.assemble=function(a){return d.assemble(a)};this.exec=function(){d.exec()};this.processAfterDomReady=function(){return!1}}};_gas.route._constructWPSearch();_gas.service={};
_gas.service._constructOnReady=function(){this.OnReady=function(a){function b(){for(key in d)if(_gas.lib.isInt(key)){var a=d[key][0],b=d[key][1];if(_gas.lib.isFunction(a))a(b);else if(window._gas[a]!=void 0)window._gas[a](b);else if(window[a])window[a](b);else console.log("Function "+a+" is undefined")}}var d=[];this.addAction=function(a,b){if(!_gas.lib.isFunction(a)&&typeof a!="string")throw"Param func must be an function or string";d[d.length]=[a,b]};this.triggerReady=function(){b()};a(document).ready(function(){b()})}};
_gas.service._constructOnReady();_gas.tracker={};
_gas.tracker._constructContainer=function(){this.Container=function(){var a=[];this.addNewTracker=function(a){this.addTracker(new _gas.Tracker(a))};this.addTracker=function(b){a[a.length]=b};this.clear=function(){a=[]};this.push=function(b){if(_gas.lib.isArray(b)&&_gas.lib.strpos(b[0],".")){var d=b[0].split(".");if(d.length>2)throw"Method call '"+b[0]+"' has invalid format";var c=this.getTracker(d[0]);b[0]=d[1];c.push(b)}else for(d=0;d<a.length;d++)a[d].push(b)};this.getTracker=function(b){for(var d=
0;d<a.length;d++)if(a[d].getName()==b+"")return a[d];throw"Tracker with name '"+b+"' is not registred";};this.hasAnyTracker=function(){return a.length>0}}};_gas.tracker._constructContainer();
_gas.tracker._constructHttpStatus=function(){this.HttpStatus=function(a){var b=!1,d=!1;this.init=function(c){!b&&d&&(b=!0,c.ajax({url:location.href,type:"HEAD",async:!0,data:{},complete:function(b){_gas.lib.inArray((b.status+"")[0],[2,3])||a.push(["_trackEvent","Error",""+b.status,location.pathname])}}))};this.setEnabled=function(){d=!0}}};_gas.tracker._constructHttpStatus();
_gas.tracker._constructLinks=function(){this.Links=function(){var a=!0,b=["pdf","doc","docx","odt","ppt","odg","ods","xls","zip","gzip","gz","rar","eps","7z","aac","arc","asf","asx","bin","csv","exe","flv","jar","msi","tar","tgz","torrent","txt","wav"];this.init=function(b){if(a){var c=this;b("a").click(function(){var a=b(this).attr("href"),e=b(this).children("img").length>0,e=b(this).text()+(e?" [img]":""),e=_gas.lib.trim(e);c.isDownloadUrl(a)?_gas.push(["_trackEvent","Download",a,e]):c.isExternalUrl(a)?
_gas.push(["_trackEvent","External link",a,e]):jQuery(this).parent("div.rss").length>0?_gas.push(["_trackEvent","RSS","Subscribe",e]):/^mailto:.+@.+\..{2,3}/.test(a)&&(a=a.replace("mailto:",""),_gas.push(["_trackEvent","Mailto clicked",a,e]))})}};this.addExtensionAsDownload=function(a){b[b.length]=a};this.setEnabled=function(b){a=!!b};this.isDownloadUrl=function(a){return RegExp("^.+\\.("+_gas.lib.implode("|",b)+")","i").test(a)};this.getDownloadExtensions=function(){return b};this.isExternalUrl=
function(a){return!a||a.length<4?!1:/^https?:\/\//i.test(a)&&!RegExp("^https?://"+window.location.hostname,"i").test(a)}}};_gas.tracker._constructLinks();_gas._constructGa();
